name: tobi

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip

  - pip:
      - git
      - streamlit
      - openai
      - trafilatura
      - requests
      - beautifulsoup4
      - lxml
      - scikit-learn
      - sentence-transformers
      - python-dotenv
      - google-api-python-client
      - google-auth
      - google-auth-httplib2
      - google-auth-oauthlib
      - torch
      - torchvision
      - torchaudio
